site_name: GCES - External Secrets Operator
repo_url: https://github.com/FGA-GCES/external-secrets

theme:
        name: material
        language: pt

nav:
        - Sprint 1:
                - Planning: sprint-01/planning.md
                - Review: sprint-01/review.md