site_name: GCES - External Secrets Operator
repo_url: https://github.com/FGA-GCES/external-secrets

theme:
  name: material
  language: pt

nav:
  - Sprint 1: sprint-01/review.md
  - Sprint 2: sprint-02/review.md
  - Sprint 3: sprint-03/review.md
  - Sprint 4: sprint-04/review.md
  - Sprint 5: sprint-05/review.md
  - Sprint 6: sprint-06/review.md
  - Sprint 7: sprint-07/review.md
  - Entrega Final: entrega-final/review.md
